/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jatin' at '17/9/14 8:16 PM' with Gradle 2.0
 *
 * @author jatin, @date 17/9/14 8:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
